export type PondAsset = { id: string; category: string; file: string; x: number; y: number; width: number; height: number; tags: string[] };
export const POND_SOURCE_SIZE = { width: 1672, height: 941 } as const;
export const POND_ASSETS: PondAsset[] = [
  { id: "layer_dock_boardwalk_full", category: "environment_layer", file: "layers/layer_dock_boardwalk_full.png", x: 1394, y: 54, width: 246, height: 851, tags: ["dock", "walkable"] },
  { id: "layer_rock_bank_full", category: "environment_layer", file: "layers/layer_rock_bank_full.png", x: 980, y: 50, width: 440, height: 845, tags: ["rocky_bank", "collision"] },
  { id: "layer_right_shore_bank", category: "environment_layer", file: "layers/layer_right_shore_bank.png", x: 1532, y: 55, width: 113, height: 830, tags: ["shore", "non_water"] },
  { id: "layer_water_playfield", category: "environment_layer", file: "layers/layer_water_playfield.png", x: 35, y: 50, width: 1085, height: 845, tags: ["water", "playfield"] },
  { id: "duck_01_top", category: "duck", file: "sprites/duck_01_top.png", x: 785, y: 145, width: 53, height: 85, tags: ["animal", "sprite", "npc"] },
  { id: "duck_02_mid", category: "duck", file: "sprites/duck_02_mid.png", x: 856, y: 252, width: 52, height: 84, tags: ["animal", "sprite", "npc"] },
  { id: "duck_03_lower_left", category: "duck", file: "sprites/duck_03_lower_left.png", x: 814, y: 390, width: 58, height: 90, tags: ["animal", "sprite", "npc"] },
  { id: "duck_04_lower_right", category: "duck", file: "sprites/duck_04_lower_right.png", x: 884, y: 378, width: 56, height: 92, tags: ["animal", "sprite", "npc"] },
  { id: "person_01_on_dock", category: "character", file: "sprites/person_01_on_dock.png", x: 1455, y: 428, width: 77, height: 65, tags: ["human", "npc", "sprite"] },
  { id: "reeds_01_top_left", category: "reeds", file: "sprites/reeds_01_top_left.png", x: 35, y: 18, width: 103, height: 142, tags: ["cattail", "plant", "decoration"] },
  { id: "reeds_02_left_mid", category: "reeds", file: "sprites/reeds_02_left_mid.png", x: 29, y: 585, width: 61, height: 110, tags: ["cattail", "plant", "decoration"] },
  { id: "reeds_03_left_bottom", category: "reeds", file: "sprites/reeds_03_left_bottom.png", x: 31, y: 716, width: 97, height: 170, tags: ["cattail", "plant", "decoration"] },
  { id: "reeds_04_bottom_left", category: "reeds", file: "sprites/reeds_04_bottom_left.png", x: 370, y: 775, width: 145, height: 117, tags: ["cattail", "plant", "decoration"] },
  { id: "reeds_05_bottom_center", category: "reeds", file: "sprites/reeds_05_bottom_center.png", x: 728, y: 784, width: 82, height: 110, tags: ["cattail", "plant", "decoration"] },
  { id: "sparkles_01_upper_left", category: "sparkles", file: "sprites/sparkles_01_upper_left.png", x: 350, y: 175, width: 65, height: 45, tags: ["water", "fx"] },
  { id: "sparkles_02_left_mid", category: "sparkles", file: "sprites/sparkles_02_left_mid.png", x: 200, y: 580, width: 115, height: 45, tags: ["water", "fx"] },
  { id: "sparkles_03_center", category: "sparkles", file: "sprites/sparkles_03_center.png", x: 478, y: 505, width: 57, height: 47, tags: ["water", "fx"] },
  { id: "sparkles_04_bottom_left", category: "sparkles", file: "sprites/sparkles_04_bottom_left.png", x: 330, y: 795, width: 80, height: 42, tags: ["water", "fx"] },
  { id: "sparkles_05_mid_bottom", category: "sparkles", file: "sprites/sparkles_05_mid_bottom.png", x: 665, y: 620, width: 80, height: 45, tags: ["water", "fx"] },
  { id: "sparkles_06_duck_zone", category: "sparkles", file: "sprites/sparkles_06_duck_zone.png", x: 825, y: 350, width: 120, height: 120, tags: ["water", "fx"] },
  { id: "underwater_rock_01_upper_mid", category: "underwater_rock", file: "sprites/underwater_rock_01_upper_mid.png", x: 650, y: 68, width: 110, height: 87, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_02_upper_mid_right", category: "underwater_rock", file: "sprites/underwater_rock_02_upper_mid_right.png", x: 744, y: 70, width: 106, height: 88, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_03_top_right", category: "underwater_rock", file: "sprites/underwater_rock_03_top_right.png", x: 915, y: 104, width: 90, height: 92, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_04_mid_left", category: "underwater_rock", file: "sprites/underwater_rock_04_mid_left.png", x: 692, y: 242, width: 88, height: 93, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_05_mid", category: "underwater_rock", file: "sprites/underwater_rock_05_mid.png", x: 810, y: 216, width: 120, height: 99, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_06_mid_right", category: "underwater_rock", file: "sprites/underwater_rock_06_mid_right.png", x: 920, y: 285, width: 92, height: 100, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_07_lower_mid_left", category: "underwater_rock", file: "sprites/underwater_rock_07_lower_mid_left.png", x: 640, y: 545, width: 90, height: 110, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_08_lower_mid", category: "underwater_rock", file: "sprites/underwater_rock_08_lower_mid.png", x: 745, y: 565, width: 93, height: 110, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_09_lower_right", category: "underwater_rock", file: "sprites/underwater_rock_09_lower_right.png", x: 830, y: 690, width: 100, height: 125, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_10_bottom_mid", category: "underwater_rock", file: "sprites/underwater_rock_10_bottom_mid.png", x: 680, y: 725, width: 105, height: 120, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_11_bottom_left", category: "underwater_rock", file: "sprites/underwater_rock_11_bottom_left.png", x: 610, y: 650, width: 90, height: 110, tags: ["underwater", "rock", "decoration"] },
  { id: "underwater_rock_12_right_edge", category: "underwater_rock", file: "sprites/underwater_rock_12_right_edge.png", x: 960, y: 645, width: 120, height: 130, tags: ["underwater", "rock", "decoration"] },
  { id: "rock_01_top_peach", category: "rock", file: "sprites/rock_01_top_peach.png", x: 1302, y: 50, width: 116, height: 98, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_02_top_white_large", category: "rock", file: "sprites/rock_02_top_white_large.png", x: 1205, y: 58, width: 114, height: 102, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_03_top_gray_white", category: "rock", file: "sprites/rock_03_top_gray_white.png", x: 1112, y: 80, width: 98, height: 98, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_04_upper_brown_left", category: "rock", file: "sprites/rock_04_upper_brown_left.png", x: 1017, y: 142, width: 94, height: 96, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_05_upper_peach_right", category: "rock", file: "sprites/rock_05_upper_peach_right.png", x: 1248, y: 128, width: 114, height: 119, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_06_upper_gray_center", category: "rock", file: "sprites/rock_06_upper_gray_center.png", x: 1144, y: 168, width: 94, height: 80, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_07_upper_small_white", category: "rock", file: "sprites/rock_07_upper_small_white.png", x: 1324, y: 180, width: 64, height: 74, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_08_mid_white_left", category: "rock", file: "sprites/rock_08_mid_white_left.png", x: 1087, y: 240, width: 101, height: 102, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_09_mid_light_center", category: "rock", file: "sprites/rock_09_mid_light_center.png", x: 1172, y: 210, width: 95, height: 102, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_10_mid_peach_right", category: "rock", file: "sprites/rock_10_mid_peach_right.png", x: 1291, y: 248, width: 110, height: 108, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_11_mid_gray_small", category: "rock", file: "sprites/rock_11_mid_gray_small.png", x: 1202, y: 292, width: 86, height: 88, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_12_mid_white_right_small", category: "rock", file: "sprites/rock_12_mid_white_right_small.png", x: 1340, y: 334, width: 75, height: 86, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_13_mid_brown_left", category: "rock", file: "sprites/rock_13_mid_brown_left.png", x: 1035, y: 310, width: 113, height: 122, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_14_mid_brown_farleft", category: "rock", file: "sprites/rock_14_mid_brown_farleft.png", x: 980, y: 338, width: 96, height: 110, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_15_mid_white_pink_left", category: "rock", file: "sprites/rock_15_mid_white_pink_left.png", x: 1106, y: 368, width: 119, height: 112, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_16_mid_gray_center", category: "rock", file: "sprites/rock_16_mid_gray_center.png", x: 1190, y: 405, width: 100, height: 105, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_17_mid_beige_large_right", category: "rock", file: "sprites/rock_17_mid_beige_large_right.png", x: 1279, y: 404, width: 129, height: 126, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_18_lower_brown_left", category: "rock", file: "sprites/rock_18_lower_brown_left.png", x: 1004, y: 444, width: 118, height: 114, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_19_lower_pink_large", category: "rock", file: "sprites/rock_19_lower_pink_large.png", x: 1110, y: 478, width: 161, height: 142, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_20_lower_white_right", category: "rock", file: "sprites/rock_20_lower_white_right.png", x: 1243, y: 500, width: 135, height: 126, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_21_lower_gray_left", category: "rock", file: "sprites/rock_21_lower_gray_left.png", x: 1043, y: 528, width: 135, height: 130, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_22_lower_pink_small", category: "rock", file: "sprites/rock_22_lower_pink_small.png", x: 1130, y: 604, width: 118, height: 112, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_23_lower_white_center_right", category: "rock", file: "sprites/rock_23_lower_white_center_right.png", x: 1222, y: 608, width: 148, height: 116, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_24_lower_beige_edge", category: "rock", file: "sprites/rock_24_lower_beige_edge.png", x: 1327, y: 612, width: 90, height: 112, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_25_lower_gray_far_left", category: "rock", file: "sprites/rock_25_lower_gray_far_left.png", x: 1001, y: 608, width: 109, height: 122, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_26_bottom_gray_left", category: "rock", file: "sprites/rock_26_bottom_gray_left.png", x: 1058, y: 675, width: 131, height: 115, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_27_bottom_white_large", category: "rock", file: "sprites/rock_27_bottom_white_large.png", x: 1188, y: 675, width: 166, height: 159, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_28_bottom_beige_right", category: "rock", file: "sprites/rock_28_bottom_beige_right.png", x: 1317, y: 707, width: 101, height: 120, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_29_bottom_pale_left", category: "rock", file: "sprites/rock_29_bottom_pale_left.png", x: 1111, y: 748, width: 136, height: 122, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_30_bottom_beige_center", category: "rock", file: "sprites/rock_30_bottom_beige_center.png", x: 1221, y: 770, width: 129, height: 120, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_31_bottom_white_far_left", category: "rock", file: "sprites/rock_31_bottom_white_far_left.png", x: 1034, y: 775, width: 111, height: 117, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_32_top_tiny_gray", category: "rock", file: "sprites/rock_32_top_tiny_gray.png", x: 1262, y: 54, width: 58, height: 50, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_33_upper_light_round", category: "rock", file: "sprites/rock_33_upper_light_round.png", x: 1180, y: 248, width: 62, height: 72, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_34_upper_round_center", category: "rock", file: "sprites/rock_34_upper_round_center.png", x: 1227, y: 331, width: 68, height: 74, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_35_right_mid_gray", category: "rock", file: "sprites/rock_35_right_mid_gray.png", x: 1354, y: 457, width: 66, height: 104, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_36_bottom_small_white", category: "rock", file: "sprites/rock_36_bottom_small_white.png", x: 1082, y: 720, width: 82, height: 92, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_37_bottom_small_pink", category: "rock", file: "sprites/rock_37_bottom_small_pink.png", x: 1158, y: 716, width: 90, height: 76, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_38_bottom_edge_white", category: "rock", file: "sprites/rock_38_bottom_edge_white.png", x: 1072, y: 818, width: 93, height: 76, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_39_mid_gray_pebble", category: "rock", file: "sprites/rock_39_mid_gray_pebble.png", x: 1128, y: 300, width: 62, height: 64, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_40_mid_pink_pebble", category: "rock", file: "sprites/rock_40_mid_pink_pebble.png", x: 1160, y: 333, width: 71, height: 77, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_41_lower_left_small_brown", category: "rock", file: "sprites/rock_41_lower_left_small_brown.png", x: 965, y: 520, width: 95, height: 100, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_42_upper_left_small_brown", category: "rock", file: "sprites/rock_42_upper_left_small_brown.png", x: 972, y: 220, width: 88, height: 92, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_43_center_greenish_shallow", category: "rock", file: "sprites/rock_43_center_greenish_shallow.png", x: 925, y: 365, width: 97, height: 105, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_44_lower_center_brown", category: "rock", file: "sprites/rock_44_lower_center_brown.png", x: 945, y: 720, width: 109, height: 130, tags: ["rock", "obstacle", "decoration"] },
  { id: "rock_45_top_water_edge_brown", category: "rock", file: "sprites/rock_45_top_water_edge_brown.png", x: 1006, y: 70, width: 104, height: 75, tags: ["rock", "obstacle", "decoration"] },
];